### 풀이 영상: https://youtu.be/XAT0qvN5tnA

## 작업형1 문제
### 1-1. age 컬럼의 3사분위수와 1사분위수의 차를 절대값으로 구하고, 소수점 버려서, 정수로 출력
- data_path: ../input/bigdatacertificationkr/basic1.csv

In [1]:
import pandas as pd
df = pd.read_csv("../input/bigdatacertificationkr/basic1.csv")

import math
Q3 = df['age'].quantile(0.75)
Q1 = df['age'].quantile(0.25)
IQR = Q3 - Q1

print(math.trunc(abs(Q3-Q1)))

50

### 1-2.(loves반응+wows반응)/(reactions반응) 비율이 0.4보다 크고 0.5보다 작으면서, type 컬럼이 'video'인 데이터의 갯수
- data_path: ../input/big-data-analytics-certification-kr-2022/fb.csv

In [2]:
import pandas as pd
df = pd.read_csv("../input/big-data-analytics-certification-kr-2022/fb.csv")

df['new'] = (df['loves'] + df['wows']) / df['reactions']
new_df = df[(df['new']>0.4) & (df['new']<0.5) & (df['type']=='video')]
print(len(new_df))

90

### 1-3. date_added가 2018년 1월 이면서 country가 United Kingdom 단독 제작인 데이터의 갯수
- data_path: ../input/big-data-analytics-certification-kr-2022/nf.csv

In [3]:
import pandas as pd
df = pd.read_csv("../input/big-data-analytics-certification-kr-2022/nf.csv")

df['date_added'] = df['date_added'].astype('datetime64')

df['year'] = df['date_added'].dt.year
df['month'] = df['date_added'].dt.month
df['day'] = df['date_added'].dt.day

len(df[(df['country'] == 'United Kingdom') & (df['year'] == 2018) & (df['month'] == 1)])

6

## 작업형1 풀이
### 1-1. age 컬럼의 3사분위수와 1사분위수의 차를 절대값으로 구하고, 소수점 버려서, 정수로 출력
- data_path: ../input/bigdatacertificationkr/basic1.csv

In [4]:
import pandas as pd
df = pd.read_csv("../input/bigdatacertificationkr/basic1.csv")
# print("1사분위: ",df['age'].quantile(0.25))
# print("3사분위: ",df['age'].quantile(0.75))

result = abs(df['age'].quantile(0.25) - df['age'].quantile(0.75))
# print("절대값 차이: ",result)

print(int(result))

50

### 1-2.(loves반응+wows반응)/(reactions반응) 비율이 0.4보다 크고 0.5보다 작으면서, status_type=='video'인 데이터의 갯수
- data_path: ../input/big-data-analytics-certification-kr-2022/fb.csv

In [5]:
import pandas as pd
df = pd.read_csv("../input/big-data-analytics-certification-kr-2022/fb.csv")
cond1 = (df['loves'] + df['wows'])/ df['reactions'] > 0.4
cond2 = (df['loves'] + df['wows'])/ df['reactions'] < 0.5
cond3 = df['type'] == 'video'

print(len(df[cond1 & cond2 & cond3]))

90

### 1-3. date_added가 2018년 1월 이면서 country가 United Kingdom 단독 제작인 데이터의 갯수¶
- data_path: ../input/big-data-analytics-certification-kr-2022/nf.csv

In [6]:
# 풀이1 datatime 활용1
import pandas as pd
df = pd.read_csv("../input/big-data-analytics-certification-kr-2022/nf.csv")

cond1 = df['country'] == "United Kingdom"

df['date_added'] = pd.to_datetime(df['date_added'])
df['year'] = df['date_added'].dt.year
df['month'] = df['date_added'].dt.month


cond2 = df['year'] == 2018
cond3 = df['month'] == 1

print(len(df[cond1 & cond2 & cond3]))

6

In [7]:
# 풀이2 datatime 활용2
import pandas as pd
df = pd.read_csv("../input/big-data-analytics-certification-kr-2022/nf.csv")

cond1 = df['country'] == "United Kingdom"

df['date_added'] = pd.to_datetime(df['date_added'])

cond2 = df['date_added'] >= '2018-1-1'
cond3 = df['date_added'] <= '2018-1-31'

print(len(df[cond1 & cond2 & cond3]))

6

In [8]:
# 풀이3 datatime + between 활용
import pandas as pd
df = pd.read_csv("../input/big-data-analytics-certification-kr-2022/nf.csv")

cond1 = df['country'] == "United Kingdom"
df['date_added'] = pd.to_datetime(df['date_added'])
cond2 = df['date_added'].between('2018-1-1', '2018-1-31')
print(len(df[cond1 & cond2]))

6

In [9]:
# 풀이4
import pandas as pd
df = pd.read_csv("../input/big-data-analytics-certification-kr-2022/nf.csv")

cond1 = df['country'] == "United Kingdom"

df['date_added'] = df['date_added'].fillna("")

str1 = "2018"
str2 = "January"
cond2 = df['date_added'].str.contains(str1)
cond3 = df['date_added'].str.contains(str2)

print(len(df[cond1 & cond2 & cond3]))

6

### (추가 문제) 4. 그런데 만약 'country'컬럼에 대소문자 함께 있고, 띄어쓰기가 있는 것도 있고 없는 것도 있다면?

In [10]:
import pandas as pd
df = pd.read_csv("../input/big-data-analytics-certification-kr-2022/nf.csv")

# 띄어쓰기 제거
df['country'] = df['country'].str.replace(' ','')

# 소문자로 변경
df['country'] = df['country'].str.lower()
df['country']

cond1 = df['country'] == "unitedkingdom"

df['date_added'] = pd.to_datetime(df['date_added'])
df['year'] = df['date_added'].dt.year
df['month'] = df['date_added'].dt.month


cond2 = df['year'] == 2018
cond3 = df['month'] == 1

print(len(df[cond1 & cond2 & cond3]))

6